default: &default
  adapter: postgresql

development:
  <<: *default
  database: find_a_pair_development

test:
  <<: *default
  database: find_a_pair_test

production:
  <<: *default
  database: find_a_pair_production

